export const REQUEST_FAILED = 'REQUEST_FAILED';

export const ALL_USERS_FETCH_REQUESTED = 'ALL_USERS_FETCH_REQUESTED';
export const ALL_USERS_FETCH_SUCCEEDED = 'ALL_USERS_FETCH_SUCCEEDED';

export const SINGLE_USER_FETCH_REQUESTED = 'SINGLE_USER_FETCH_REQUESTED';
export const SINGLE_USER_FETCH_SUCCEEDED = 'SINGLE_USER_FETCH_SUCCEEDED';
